#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_CREATED=false

random_hex() {
  local bytes="${1:-32}"

  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi

  if command -v od >/dev/null 2>&1; then
    od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
    return
  fi

  echo "openssl or od is required to generate secrets" >&2
  return 1
}

env_has_key() {
  local key="$1"
  [[ -f "$ENV_FILE" ]] && grep -Eq "^[[:space:]]*(export[[:space:]]+)?${key}=" "$ENV_FILE"
}

ensure_env() {
  local key="$1"
  local value="$2"
  local comment="${3:-}"

  if env_has_key "$key"; then
    return
  fi

  if [[ -n "$comment" ]]; then
    printf '\n%s\n' "$comment" >>"$ENV_FILE"
  fi
  printf '%s=%s\n' "$key" "$value" >>"$ENV_FILE"
  echo "[init-env] added $key"
}

ensure_secret_env() {
  local key="$1"
  if env_has_key "$key"; then
    return
  fi
  ensure_env "$key" "$(random_hex 32)"
}

if [[ ! -f "$ENV_FILE" ]]; then
  cat >"$ENV_FILE" <<EOF
# OpenShare Docker Compose environment.
# Generated by docker/init-env.sh. Keep these secrets private.
EOF

  chmod 600 "$ENV_FILE"
  ENV_CREATED=true
  echo "[init-env] created $ENV_FILE"
else
  echo "[init-env] found existing $ENV_FILE"
fi

ensure_secret_env "OPENSHARE_SESSION_SECRET"
ensure_secret_env "MEILI_MASTER_KEY"
ensure_env "OPENSHARE_SEARCH_ENGINE_ENABLED" "true" "# Set to false if you do not want to run Meilisearch-backed search."
ensure_env "OPENSHARE_HTTP_PORT" "8080" "# Host ports."
ensure_env "MEILI_HTTP_PORT" "7700"
ensure_env "OPENSHARE_DATA_PATH" "./data" "# Host directories mounted into containers."
ensure_env "OPENSHARE_IMPORTS_PATH" "./imports"
ensure_env "MEILI_DATA_PATH" "./meili_data"
ensure_env "OPENSHARE_IMPORTS_CONTAINER_PATH" "/imports"
ensure_env "OPENSHARE_IMAGE" "ghcr.io/crescentm/openshare:latest" "# OpenShare image used by docker/docker-compose.yml."
ensure_env "OPENSHARE_CONTAINER_NAME" "openshare" "# Optional names."
ensure_env "OPENSHARE_WORKER_CONTAINER_NAME" "openshare-worker"
ensure_env "MEILI_CONTAINER_NAME" "openshare-meilisearch"

if [[ "$ENV_CREATED" == false ]]; then
  echo "[init-env] kept existing values and filled missing defaults"
fi

mkdir -p "$SCRIPT_DIR/data" "$SCRIPT_DIR/imports" "$SCRIPT_DIR/meili_data"

echo "[init-env] prepared Docker data directories:"
echo "  $SCRIPT_DIR/data"
echo "  $SCRIPT_DIR/imports"
echo "  $SCRIPT_DIR/meili_data"
echo
echo "[init-env] next:"
echo "  cd \"$SCRIPT_DIR\""
echo "  docker compose up -d"
