#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

random_hex() {
  local bytes="${1:-32}"

  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi

  if command -v od >/dev/null 2>&1; then
    od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
    return
  fi

  echo "openssl or od is required to generate secrets" >&2
  return 1
}

if [[ -f "$ENV_FILE" ]]; then
  echo "[init-env] .env already exists: $ENV_FILE"
  echo "[init-env] keeping existing values"
else
  session_secret="$(random_hex 32)"
  meili_master_key="$(random_hex 32)"

  cat >"$ENV_FILE" <<EOF
# OpenShare Docker Compose environment.
# Generated by docker/init-env.sh. Keep these secrets private.

OPENSHARE_SESSION_SECRET=$session_secret
MEILI_MASTER_KEY=$meili_master_key

# Set to false if you do not want to run Meilisearch-backed search.
OPENSHARE_SEARCH_ENGINE_ENABLED=true

# Host ports.
OPENSHARE_HTTP_PORT=8080
MEILI_HTTP_PORT=7700

# Host directories mounted into containers.
OPENSHARE_DATA_PATH=./data
OPENSHARE_IMPORTS_PATH=./imports
MEILI_DATA_PATH=./meili_data
OPENSHARE_IMPORTS_CONTAINER_PATH=/imports

# Optional names.
OPENSHARE_CONTAINER_NAME=openshare
OPENSHARE_WORKER_CONTAINER_NAME=openshare-worker
MEILI_CONTAINER_NAME=openshare-meilisearch
EOF

  chmod 600 "$ENV_FILE"
  echo "[init-env] created $ENV_FILE"
fi

mkdir -p "$SCRIPT_DIR/data" "$SCRIPT_DIR/imports" "$SCRIPT_DIR/meili_data"

echo "[init-env] prepared Docker data directories:"
echo "  $SCRIPT_DIR/data"
echo "  $SCRIPT_DIR/imports"
echo "  $SCRIPT_DIR/meili_data"
echo
echo "[init-env] next:"
echo "  cd \"$SCRIPT_DIR\""
echo "  docker compose up -d --build"
