#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_DATA_DIR="${OPENSHARE_LOCAL_DATA_DIR:-$ROOT_DIR/.localdata}"
LOG_DIR="$LOCAL_DATA_DIR/logs"
ENV_FILE="$LOCAL_DATA_DIR/dev.env"
BACKEND_LOG="$LOG_DIR/backend.log"
WORKER_LOG="$LOG_DIR/worker.log"
FRONTEND_LOG="$LOG_DIR/frontend.log"

random_hex() {
  local bytes="${1:-32}"

  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi

  if command -v od >/dev/null 2>&1; then
    od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
    return
  fi

  echo "openssl or od is required to generate secrets" >&2
  return 1
}

mkdir -p "$LOG_DIR"

if [[ ! -f "$ENV_FILE" ]]; then
  cat >"$ENV_FILE" <<EOF
# OpenShare local source development environment.
# Generated by scripts/dev.sh.
OPENSHARE_SESSION_SECRET=$(random_hex 32)
EOF
  chmod 600 "$ENV_FILE"
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

export OPENSHARE_SERVER_HOST="${OPENSHARE_SERVER_HOST:-127.0.0.1}"
export OPENSHARE_SERVER_PORT="${OPENSHARE_SERVER_PORT:-8080}"
export OPENSHARE_DATABASE_PATH="${OPENSHARE_DATABASE_PATH:-$LOCAL_DATA_DIR/openshare.db}"
export OPENSHARE_STORAGE_ROOT="${OPENSHARE_STORAGE_ROOT:-$LOCAL_DATA_DIR}"
export OPENSHARE_SEARCH_ENGINE_ENABLED="${OPENSHARE_SEARCH_ENGINE_ENABLED:-false}"

FRONTEND_HOST="${OPENSHARE_FRONTEND_HOST:-127.0.0.1}"
FRONTEND_PORT="${OPENSHARE_FRONTEND_PORT:-5173}"

echo "==> Installing frontend dependencies"
(
  cd "$ROOT_DIR/frontend"
  npm install >"$FRONTEND_LOG" 2>&1
)

echo "==> Starting frontend dev server"
(
  cd "$ROOT_DIR/frontend"
  npm run dev -- --host "$FRONTEND_HOST" --port "$FRONTEND_PORT" >"$FRONTEND_LOG" 2>&1
) &
FRONTEND_PID=$!

echo "==> Starting backend server"
(
  cd "$ROOT_DIR/backend"
  go run ./cmd/server >"$BACKEND_LOG" 2>&1
) &
BACKEND_PID=$!

echo "==> Starting sync worker"
(
  cd "$ROOT_DIR/backend"
  go run ./cmd/worker >"$WORKER_LOG" 2>&1
) &
WORKER_PID=$!

cleanup() {
  kill "$FRONTEND_PID" "$BACKEND_PID" "$WORKER_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

echo
echo "OpenShare is starting"
echo "  Public     : http://$FRONTEND_HOST:$FRONTEND_PORT/"
echo "  Admin      : http://$FRONTEND_HOST:$FRONTEND_PORT/admin"
echo "  API Health : http://$OPENSHARE_SERVER_HOST:$OPENSHARE_SERVER_PORT/healthz"
echo "  Data       : $LOCAL_DATA_DIR"
echo "  Logs       : $LOG_DIR"
echo

for _ in {1..30}; do
  if [[ -f "$BACKEND_LOG" ]]; then
    admin_line="$(grep -E '\[bootstrap\] super admin initialized; username=.* password=.*' "$BACKEND_LOG" | tail -n 1 || true)"
    if [[ -n "$admin_line" ]]; then
      echo "Initial super admin:"
      echo "$admin_line"
      echo
      break
    fi
  fi
  sleep 1
done

echo "Press Ctrl+C to stop"
wait
